// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ai_research_jobs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAIResearchJob = `-- name: CreateAIResearchJob :one

INSERT INTO ai_research_jobs (
    company_name,
    domain,
    status
) VALUES (
    $1, $2, $3
)
RETURNING id, company_name, domain, status, result_json, error_message, created_at, completed_at
`

type CreateAIResearchJobParams struct {
	CompanyName string `json:"company_name"`
	Domain      string `json:"domain"`
	Status      string `json:"status"`
}

// internal/db/queries/ai_research_jobs.sql
func (q *Queries) CreateAIResearchJob(ctx context.Context, arg CreateAIResearchJobParams) (AiResearchJob, error) {
	row := q.db.QueryRow(ctx, createAIResearchJob, arg.CompanyName, arg.Domain, arg.Status)
	var i AiResearchJob
	err := row.Scan(
		&i.ID,
		&i.CompanyName,
		&i.Domain,
		&i.Status,
		&i.ResultJson,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getAIResearchJobByID = `-- name: GetAIResearchJobByID :one
SELECT id, company_name, domain, status, result_json, error_message, created_at, completed_at FROM ai_research_jobs
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetAIResearchJobByID(ctx context.Context, id pgtype.UUID) (AiResearchJob, error) {
	row := q.db.QueryRow(ctx, getAIResearchJobByID, id)
	var i AiResearchJob
	err := row.Scan(
		&i.ID,
		&i.CompanyName,
		&i.Domain,
		&i.Status,
		&i.ResultJson,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const listAIResearchJobs = `-- name: ListAIResearchJobs :many
SELECT id, company_name, domain, status, result_json, error_message, created_at, completed_at FROM ai_research_jobs
ORDER BY created_at DESC
`

func (q *Queries) ListAIResearchJobs(ctx context.Context) ([]AiResearchJob, error) {
	rows, err := q.db.Query(ctx, listAIResearchJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AiResearchJob
	for rows.Next() {
		var i AiResearchJob
		if err := rows.Scan(
			&i.ID,
			&i.CompanyName,
			&i.Domain,
			&i.Status,
			&i.ResultJson,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAIResearchJobStatus = `-- name: UpdateAIResearchJobStatus :one
UPDATE ai_research_jobs
SET status = $2,
    result_json = $3,
    error_message = $4,
    completed_at = $5
WHERE id = $1
RETURNING id, company_name, domain, status, result_json, error_message, created_at, completed_at
`

type UpdateAIResearchJobStatusParams struct {
	ID           pgtype.UUID        `json:"id"`
	Status       string             `json:"status"`
	ResultJson   []byte             `json:"result_json"`
	ErrorMessage string             `json:"error_message"`
	CompletedAt  pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) UpdateAIResearchJobStatus(ctx context.Context, arg UpdateAIResearchJobStatusParams) (AiResearchJob, error) {
	row := q.db.QueryRow(ctx, updateAIResearchJobStatus,
		arg.ID,
		arg.Status,
		arg.ResultJson,
		arg.ErrorMessage,
		arg.CompletedAt,
	)
	var i AiResearchJob
	err := row.Scan(
		&i.ID,
		&i.CompanyName,
		&i.Domain,
		&i.Status,
		&i.ResultJson,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}
