// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: appointments.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAppointment = `-- name: CreateAppointment :one

INSERT INTO appointments (
    title,
    contact_id,
    company_id,
    deal_id,
    start_time,
    end_time,
    location,
    notes,
    ics_uid,
    assigned_to,
    type,
    is_external,
    provider,
    is_private,
    is_pushed
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15
)
RETURNING id, title, contact_id, company_id, deal_id, start_time, end_time, location, notes, ics_uid, created_at, assigned_to, type, is_external, provider, is_private, is_pushed, updated_at
`

type CreateAppointmentParams struct {
	Title      string             `json:"title"`
	ContactID  pgtype.UUID        `json:"contact_id"`
	CompanyID  pgtype.UUID        `json:"company_id"`
	DealID     pgtype.UUID        `json:"deal_id"`
	StartTime  pgtype.Timestamptz `json:"start_time"`
	EndTime    pgtype.Timestamptz `json:"end_time"`
	Location   string             `json:"location"`
	Notes      string             `json:"notes"`
	IcsUid     string             `json:"ics_uid"`
	AssignedTo string             `json:"assigned_to"`
	Type       string             `json:"type"`
	IsExternal bool               `json:"is_external"`
	Provider   string             `json:"provider"`
	IsPrivate  bool               `json:"is_private"`
	IsPushed   bool               `json:"is_pushed"`
}

// internal/db/queries/appointments.sql
func (q *Queries) CreateAppointment(ctx context.Context, arg CreateAppointmentParams) (Appointment, error) {
	row := q.db.QueryRow(ctx, createAppointment,
		arg.Title,
		arg.ContactID,
		arg.CompanyID,
		arg.DealID,
		arg.StartTime,
		arg.EndTime,
		arg.Location,
		arg.Notes,
		arg.IcsUid,
		arg.AssignedTo,
		arg.Type,
		arg.IsExternal,
		arg.Provider,
		arg.IsPrivate,
		arg.IsPushed,
	)
	var i Appointment
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.ContactID,
		&i.CompanyID,
		&i.DealID,
		&i.StartTime,
		&i.EndTime,
		&i.Location,
		&i.Notes,
		&i.IcsUid,
		&i.CreatedAt,
		&i.AssignedTo,
		&i.Type,
		&i.IsExternal,
		&i.Provider,
		&i.IsPrivate,
		&i.IsPushed,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAppointment = `-- name: DeleteAppointment :exec
DELETE FROM appointments
WHERE id = $1
`

func (q *Queries) DeleteAppointment(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAppointment, id)
	return err
}

const getAppointmentByID = `-- name: GetAppointmentByID :one
SELECT id, title, contact_id, company_id, deal_id, start_time, end_time, location, notes, ics_uid, created_at, assigned_to, type, is_external, provider, is_private, is_pushed, updated_at FROM appointments
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetAppointmentByID(ctx context.Context, id pgtype.UUID) (Appointment, error) {
	row := q.db.QueryRow(ctx, getAppointmentByID, id)
	var i Appointment
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.ContactID,
		&i.CompanyID,
		&i.DealID,
		&i.StartTime,
		&i.EndTime,
		&i.Location,
		&i.Notes,
		&i.IcsUid,
		&i.CreatedAt,
		&i.AssignedTo,
		&i.Type,
		&i.IsExternal,
		&i.Provider,
		&i.IsPrivate,
		&i.IsPushed,
		&i.UpdatedAt,
	)
	return i, err
}

const listAppointments = `-- name: ListAppointments :many
SELECT id, title, contact_id, company_id, deal_id, start_time, end_time, location, notes, ics_uid, created_at, assigned_to, type, is_external, provider, is_private, is_pushed, updated_at FROM appointments
ORDER BY start_time ASC
`

func (q *Queries) ListAppointments(ctx context.Context) ([]Appointment, error) {
	rows, err := q.db.Query(ctx, listAppointments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Appointment
	for rows.Next() {
		var i Appointment
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.ContactID,
			&i.CompanyID,
			&i.DealID,
			&i.StartTime,
			&i.EndTime,
			&i.Location,
			&i.Notes,
			&i.IcsUid,
			&i.CreatedAt,
			&i.AssignedTo,
			&i.Type,
			&i.IsExternal,
			&i.Provider,
			&i.IsPrivate,
			&i.IsPushed,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAppointment = `-- name: UpdateAppointment :one
UPDATE appointments
SET title = $2,
    contact_id = $3,
    start_time = $4,
    end_time = $5,
    location = $6,
    notes = $7,
    assigned_to = $8,
    type = $9,
    updated_at = NOW()
WHERE id = $1
RETURNING id, title, contact_id, company_id, deal_id, start_time, end_time, location, notes, ics_uid, created_at, assigned_to, type, is_external, provider, is_private, is_pushed, updated_at
`

type UpdateAppointmentParams struct {
	ID         pgtype.UUID        `json:"id"`
	Title      string             `json:"title"`
	ContactID  pgtype.UUID        `json:"contact_id"`
	StartTime  pgtype.Timestamptz `json:"start_time"`
	EndTime    pgtype.Timestamptz `json:"end_time"`
	Location   string             `json:"location"`
	Notes      string             `json:"notes"`
	AssignedTo string             `json:"assigned_to"`
	Type       string             `json:"type"`
}

func (q *Queries) UpdateAppointment(ctx context.Context, arg UpdateAppointmentParams) (Appointment, error) {
	row := q.db.QueryRow(ctx, updateAppointment,
		arg.ID,
		arg.Title,
		arg.ContactID,
		arg.StartTime,
		arg.EndTime,
		arg.Location,
		arg.Notes,
		arg.AssignedTo,
		arg.Type,
	)
	var i Appointment
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.ContactID,
		&i.CompanyID,
		&i.DealID,
		&i.StartTime,
		&i.EndTime,
		&i.Location,
		&i.Notes,
		&i.IcsUid,
		&i.CreatedAt,
		&i.AssignedTo,
		&i.Type,
		&i.IsExternal,
		&i.Provider,
		&i.IsPrivate,
		&i.IsPushed,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAppointmentPushStatus = `-- name: UpdateAppointmentPushStatus :one
UPDATE appointments
SET is_pushed = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, title, contact_id, company_id, deal_id, start_time, end_time, location, notes, ics_uid, created_at, assigned_to, type, is_external, provider, is_private, is_pushed, updated_at
`

type UpdateAppointmentPushStatusParams struct {
	ID       pgtype.UUID `json:"id"`
	IsPushed bool        `json:"is_pushed"`
}

func (q *Queries) UpdateAppointmentPushStatus(ctx context.Context, arg UpdateAppointmentPushStatusParams) (Appointment, error) {
	row := q.db.QueryRow(ctx, updateAppointmentPushStatus, arg.ID, arg.IsPushed)
	var i Appointment
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.ContactID,
		&i.CompanyID,
		&i.DealID,
		&i.StartTime,
		&i.EndTime,
		&i.Location,
		&i.Notes,
		&i.IcsUid,
		&i.CreatedAt,
		&i.AssignedTo,
		&i.Type,
		&i.IsExternal,
		&i.Provider,
		&i.IsPrivate,
		&i.IsPushed,
		&i.UpdatedAt,
	)
	return i, err
}
