// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: call_activities.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCallActivity = `-- name: CreateCallActivity :one

INSERT INTO call_activities (
    contact_id,
    duration_seconds,
    disposition,
    notes
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, contact_id, duration_seconds, disposition, notes, created_at
`

type CreateCallActivityParams struct {
	ContactID       pgtype.UUID `json:"contact_id"`
	DurationSeconds int32       `json:"duration_seconds"`
	Disposition     string      `json:"disposition"`
	Notes           string      `json:"notes"`
}

// internal/db/queries/call_activities.sql
func (q *Queries) CreateCallActivity(ctx context.Context, arg CreateCallActivityParams) (CallActivity, error) {
	row := q.db.QueryRow(ctx, createCallActivity,
		arg.ContactID,
		arg.DurationSeconds,
		arg.Disposition,
		arg.Notes,
	)
	var i CallActivity
	err := row.Scan(
		&i.ID,
		&i.ContactID,
		&i.DurationSeconds,
		&i.Disposition,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const listCallActivitiesByContact = `-- name: ListCallActivitiesByContact :many
SELECT id, contact_id, duration_seconds, disposition, notes, created_at FROM call_activities
WHERE contact_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListCallActivitiesByContact(ctx context.Context, contactID pgtype.UUID) ([]CallActivity, error) {
	rows, err := q.db.Query(ctx, listCallActivitiesByContact, contactID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CallActivity
	for rows.Next() {
		var i CallActivity
		if err := rows.Scan(
			&i.ID,
			&i.ContactID,
			&i.DurationSeconds,
			&i.Disposition,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentCallActivities = `-- name: ListRecentCallActivities :many
SELECT id, contact_id, duration_seconds, disposition, notes, created_at FROM call_activities
ORDER BY created_at DESC
LIMIT $1
`

func (q *Queries) ListRecentCallActivities(ctx context.Context, limit int32) ([]CallActivity, error) {
	rows, err := q.db.Query(ctx, listRecentCallActivities, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CallActivity
	for rows.Next() {
		var i CallActivity
		if err := rows.Scan(
			&i.ID,
			&i.ContactID,
			&i.DurationSeconds,
			&i.Disposition,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
