// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: companies.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCompany = `-- name: CreateCompany :one
INSERT INTO companies (
    name,
    domain,
    phone,
    email,
    address_street,
    address_zip,
    address_city,
    address_country,
    custom_fields
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, name, domain, phone, email, address_street, address_zip, address_city, address_country, custom_fields, created_at, updated_at
`

type CreateCompanyParams struct {
	Name           string      `json:"name"`
	Domain         pgtype.Text `json:"domain"`
	Phone          pgtype.Text `json:"phone"`
	Email          pgtype.Text `json:"email"`
	AddressStreet  pgtype.Text `json:"address_street"`
	AddressZip     pgtype.Text `json:"address_zip"`
	AddressCity    pgtype.Text `json:"address_city"`
	AddressCountry pgtype.Text `json:"address_country"`
	CustomFields   []byte      `json:"custom_fields"`
}

// internal/db/queries/companies.sql
func (q *Queries) CreateCompany(ctx context.Context, arg CreateCompanyParams) (Company, error) {
	row := q.db.QueryRow(ctx, createCompany,
		arg.Name,
		arg.Domain,
		arg.Phone,
		arg.Email,
		arg.AddressStreet,
		arg.AddressZip,
		arg.AddressCity,
		arg.AddressCountry,
		arg.CustomFields,
	)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Domain,
		&i.Phone,
		&i.Email,
		&i.AddressStreet,
		&i.AddressZip,
		&i.AddressCity,
		&i.AddressCountry,
		&i.CustomFields,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCompany = `-- name: DeleteCompany :exec
DELETE FROM companies
WHERE id = $1
`

func (q *Queries) DeleteCompany(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCompany, id)
	return err
}

const getCompanyByID = `-- name: GetCompanyByID :one
SELECT id, name, domain, phone, email, address_street, address_zip, address_city, address_country, custom_fields, created_at, updated_at FROM companies
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetCompanyByID(ctx context.Context, id pgtype.UUID) (Company, error) {
	row := q.db.QueryRow(ctx, getCompanyByID, id)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Domain,
		&i.Phone,
		&i.Email,
		&i.AddressStreet,
		&i.AddressZip,
		&i.AddressCity,
		&i.AddressCountry,
		&i.CustomFields,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCompanies = `-- name: ListCompanies :many
SELECT id, name, domain, phone, email, address_street, address_zip, address_city, address_country, custom_fields, created_at, updated_at FROM companies
ORDER BY name ASC
LIMIT $1 OFFSET $2
`

type ListCompaniesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListCompanies(ctx context.Context, arg ListCompaniesParams) ([]Company, error) {
	rows, err := q.db.Query(ctx, listCompanies, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Company
	for rows.Next() {
		var i Company
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Domain,
			&i.Phone,
			&i.Email,
			&i.AddressStreet,
			&i.AddressZip,
			&i.AddressCity,
			&i.AddressCountry,
			&i.CustomFields,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchCompanies = `-- name: SearchCompanies :many
SELECT id, name, domain, phone, email, address_street, address_zip, address_city, address_country, custom_fields, created_at, updated_at FROM companies
WHERE name ILIKE '%' || $1 || '%' OR domain ILIKE '%' || $1 || '%'
ORDER BY name ASC
LIMIT $2
`

type SearchCompaniesParams struct {
	Column1 pgtype.Text `json:"column_1"`
	Limit   int32       `json:"limit"`
}

func (q *Queries) SearchCompanies(ctx context.Context, arg SearchCompaniesParams) ([]Company, error) {
	rows, err := q.db.Query(ctx, searchCompanies, arg.Column1, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Company
	for rows.Next() {
		var i Company
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Domain,
			&i.Phone,
			&i.Email,
			&i.AddressStreet,
			&i.AddressZip,
			&i.AddressCity,
			&i.AddressCountry,
			&i.CustomFields,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCompany = `-- name: UpdateCompany :one
UPDATE companies
SET name = $2,
    domain = $3,
    phone = $4,
    email = $5,
    address_street = $6,
    address_zip = $7,
    address_city = $8,
    address_country = $9,
    custom_fields = $10,
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, domain, phone, email, address_street, address_zip, address_city, address_country, custom_fields, created_at, updated_at
`

type UpdateCompanyParams struct {
	ID             pgtype.UUID `json:"id"`
	Name           string      `json:"name"`
	Domain         pgtype.Text `json:"domain"`
	Phone          pgtype.Text `json:"phone"`
	Email          pgtype.Text `json:"email"`
	AddressStreet  pgtype.Text `json:"address_street"`
	AddressZip     pgtype.Text `json:"address_zip"`
	AddressCity    pgtype.Text `json:"address_city"`
	AddressCountry pgtype.Text `json:"address_country"`
	CustomFields   []byte      `json:"custom_fields"`
}

func (q *Queries) UpdateCompany(ctx context.Context, arg UpdateCompanyParams) (Company, error) {
	row := q.db.QueryRow(ctx, updateCompany,
		arg.ID,
		arg.Name,
		arg.Domain,
		arg.Phone,
		arg.Email,
		arg.AddressStreet,
		arg.AddressZip,
		arg.AddressCity,
		arg.AddressCountry,
		arg.CustomFields,
	)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Domain,
		&i.Phone,
		&i.Email,
		&i.AddressStreet,
		&i.AddressZip,
		&i.AddressCity,
		&i.AddressCountry,
		&i.CustomFields,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
