// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: contacts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createContact = `-- name: CreateContact :one
INSERT INTO contacts (
    company_id,
    first_name,
    last_name,
    email,
    phone,
    mobile,
    position,
    lead_source,
    address_street,
    address_zip,
    address_city,
    latitude,
    longitude,
    custom_fields
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14
)
RETURNING id, company_id, first_name, last_name, email, phone, mobile, position, lead_source, address_street, address_zip, address_city, latitude, longitude, custom_fields, created_at, updated_at, consent_phone, consent_email, consent_updated_at, stromverbrauch_kwh, gasverbrauch_kwh, zaehlernummer, eigentuemer_status
`

type CreateContactParams struct {
	CompanyID     pgtype.UUID   `json:"company_id"`
	FirstName     string        `json:"first_name"`
	LastName      string        `json:"last_name"`
	Email         pgtype.Text   `json:"email"`
	Phone         pgtype.Text   `json:"phone"`
	Mobile        pgtype.Text   `json:"mobile"`
	Position      pgtype.Text   `json:"position"`
	LeadSource    pgtype.Text   `json:"lead_source"`
	AddressStreet pgtype.Text   `json:"address_street"`
	AddressZip    pgtype.Text   `json:"address_zip"`
	AddressCity   pgtype.Text   `json:"address_city"`
	Latitude      pgtype.Float8 `json:"latitude"`
	Longitude     pgtype.Float8 `json:"longitude"`
	CustomFields  []byte        `json:"custom_fields"`
}

// internal/db/queries/contacts.sql
func (q *Queries) CreateContact(ctx context.Context, arg CreateContactParams) (Contact, error) {
	row := q.db.QueryRow(ctx, createContact,
		arg.CompanyID,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Phone,
		arg.Mobile,
		arg.Position,
		arg.LeadSource,
		arg.AddressStreet,
		arg.AddressZip,
		arg.AddressCity,
		arg.Latitude,
		arg.Longitude,
		arg.CustomFields,
	)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.Mobile,
		&i.Position,
		&i.LeadSource,
		&i.AddressStreet,
		&i.AddressZip,
		&i.AddressCity,
		&i.Latitude,
		&i.Longitude,
		&i.CustomFields,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ConsentPhone,
		&i.ConsentEmail,
		&i.ConsentUpdatedAt,
		&i.StromverbrauchKwh,
		&i.GasverbrauchKwh,
		&i.Zaehlernummer,
		&i.EigentuemerStatus,
	)
	return i, err
}

const deleteContact = `-- name: DeleteContact :exec
DELETE FROM contacts
WHERE id = $1
`

func (q *Queries) DeleteContact(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteContact, id)
	return err
}

const getContactByID = `-- name: GetContactByID :one
SELECT id, company_id, first_name, last_name, email, phone, mobile, position, lead_source, address_street, address_zip, address_city, latitude, longitude, custom_fields, created_at, updated_at, consent_phone, consent_email, consent_updated_at, stromverbrauch_kwh, gasverbrauch_kwh, zaehlernummer, eigentuemer_status FROM contacts
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetContactByID(ctx context.Context, id pgtype.UUID) (Contact, error) {
	row := q.db.QueryRow(ctx, getContactByID, id)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.Mobile,
		&i.Position,
		&i.LeadSource,
		&i.AddressStreet,
		&i.AddressZip,
		&i.AddressCity,
		&i.Latitude,
		&i.Longitude,
		&i.CustomFields,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ConsentPhone,
		&i.ConsentEmail,
		&i.ConsentUpdatedAt,
		&i.StromverbrauchKwh,
		&i.GasverbrauchKwh,
		&i.Zaehlernummer,
		&i.EigentuemerStatus,
	)
	return i, err
}

const listContacts = `-- name: ListContacts :many
SELECT id, company_id, first_name, last_name, email, phone, mobile, position, lead_source, address_street, address_zip, address_city, latitude, longitude, custom_fields, created_at, updated_at, consent_phone, consent_email, consent_updated_at, stromverbrauch_kwh, gasverbrauch_kwh, zaehlernummer, eigentuemer_status FROM contacts
ORDER BY last_name ASC, first_name ASC
LIMIT $1 OFFSET $2
`

type ListContactsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListContacts(ctx context.Context, arg ListContactsParams) ([]Contact, error) {
	rows, err := q.db.Query(ctx, listContacts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Contact
	for rows.Next() {
		var i Contact
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.Phone,
			&i.Mobile,
			&i.Position,
			&i.LeadSource,
			&i.AddressStreet,
			&i.AddressZip,
			&i.AddressCity,
			&i.Latitude,
			&i.Longitude,
			&i.CustomFields,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ConsentPhone,
			&i.ConsentEmail,
			&i.ConsentUpdatedAt,
			&i.StromverbrauchKwh,
			&i.GasverbrauchKwh,
			&i.Zaehlernummer,
			&i.EigentuemerStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContactsByCompany = `-- name: ListContactsByCompany :many
SELECT id, company_id, first_name, last_name, email, phone, mobile, position, lead_source, address_street, address_zip, address_city, latitude, longitude, custom_fields, created_at, updated_at, consent_phone, consent_email, consent_updated_at, stromverbrauch_kwh, gasverbrauch_kwh, zaehlernummer, eigentuemer_status FROM contacts
WHERE company_id = $1
ORDER BY last_name ASC, first_name ASC
`

func (q *Queries) ListContactsByCompany(ctx context.Context, companyID pgtype.UUID) ([]Contact, error) {
	rows, err := q.db.Query(ctx, listContactsByCompany, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Contact
	for rows.Next() {
		var i Contact
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.Phone,
			&i.Mobile,
			&i.Position,
			&i.LeadSource,
			&i.AddressStreet,
			&i.AddressZip,
			&i.AddressCity,
			&i.Latitude,
			&i.Longitude,
			&i.CustomFields,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ConsentPhone,
			&i.ConsentEmail,
			&i.ConsentUpdatedAt,
			&i.StromverbrauchKwh,
			&i.GasverbrauchKwh,
			&i.Zaehlernummer,
			&i.EigentuemerStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchContacts = `-- name: SearchContacts :many
SELECT id, company_id, first_name, last_name, email, phone, mobile, position, lead_source, address_street, address_zip, address_city, latitude, longitude, custom_fields, created_at, updated_at, consent_phone, consent_email, consent_updated_at, stromverbrauch_kwh, gasverbrauch_kwh, zaehlernummer, eigentuemer_status FROM contacts
WHERE first_name ILIKE '%' || $1 || '%'
   OR last_name ILIKE '%' || $1 || '%'
   OR email ILIKE '%' || $1 || '%'
   OR phone ILIKE '%' || $1 || '%'
ORDER BY last_name ASC
LIMIT $2
`

type SearchContactsParams struct {
	Column1 pgtype.Text `json:"column_1"`
	Limit   int32       `json:"limit"`
}

func (q *Queries) SearchContacts(ctx context.Context, arg SearchContactsParams) ([]Contact, error) {
	rows, err := q.db.Query(ctx, searchContacts, arg.Column1, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Contact
	for rows.Next() {
		var i Contact
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.Phone,
			&i.Mobile,
			&i.Position,
			&i.LeadSource,
			&i.AddressStreet,
			&i.AddressZip,
			&i.AddressCity,
			&i.Latitude,
			&i.Longitude,
			&i.CustomFields,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ConsentPhone,
			&i.ConsentEmail,
			&i.ConsentUpdatedAt,
			&i.StromverbrauchKwh,
			&i.GasverbrauchKwh,
			&i.Zaehlernummer,
			&i.EigentuemerStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateContact = `-- name: UpdateContact :one
UPDATE contacts
SET company_id = $2,
    first_name = $3,
    last_name = $4,
    email = $5,
    phone = $6,
    mobile = $7,
    position = $8,
    lead_source = $9,
    address_street = $10,
    address_zip = $11,
    address_city = $12,
    latitude = $13,
    longitude = $14,
    custom_fields = $15,
    updated_at = NOW()
WHERE id = $1
RETURNING id, company_id, first_name, last_name, email, phone, mobile, position, lead_source, address_street, address_zip, address_city, latitude, longitude, custom_fields, created_at, updated_at, consent_phone, consent_email, consent_updated_at, stromverbrauch_kwh, gasverbrauch_kwh, zaehlernummer, eigentuemer_status
`

type UpdateContactParams struct {
	ID            pgtype.UUID   `json:"id"`
	CompanyID     pgtype.UUID   `json:"company_id"`
	FirstName     string        `json:"first_name"`
	LastName      string        `json:"last_name"`
	Email         pgtype.Text   `json:"email"`
	Phone         pgtype.Text   `json:"phone"`
	Mobile        pgtype.Text   `json:"mobile"`
	Position      pgtype.Text   `json:"position"`
	LeadSource    pgtype.Text   `json:"lead_source"`
	AddressStreet pgtype.Text   `json:"address_street"`
	AddressZip    pgtype.Text   `json:"address_zip"`
	AddressCity   pgtype.Text   `json:"address_city"`
	Latitude      pgtype.Float8 `json:"latitude"`
	Longitude     pgtype.Float8 `json:"longitude"`
	CustomFields  []byte        `json:"custom_fields"`
}

func (q *Queries) UpdateContact(ctx context.Context, arg UpdateContactParams) (Contact, error) {
	row := q.db.QueryRow(ctx, updateContact,
		arg.ID,
		arg.CompanyID,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Phone,
		arg.Mobile,
		arg.Position,
		arg.LeadSource,
		arg.AddressStreet,
		arg.AddressZip,
		arg.AddressCity,
		arg.Latitude,
		arg.Longitude,
		arg.CustomFields,
	)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.Mobile,
		&i.Position,
		&i.LeadSource,
		&i.AddressStreet,
		&i.AddressZip,
		&i.AddressCity,
		&i.Latitude,
		&i.Longitude,
		&i.CustomFields,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ConsentPhone,
		&i.ConsentEmail,
		&i.ConsentUpdatedAt,
		&i.StromverbrauchKwh,
		&i.GasverbrauchKwh,
		&i.Zaehlernummer,
		&i.EigentuemerStatus,
	)
	return i, err
}
