// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deals.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDeal = `-- name: CreateDeal :one
INSERT INTO deals (
    title,
    company_id,
    contact_id,
    value,
    currency,
    stage,
    probability,
    assigned_to,
    closed_at,
    custom_fields
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING id, title, company_id, contact_id, value, currency, stage, probability, assigned_to, closed_at, custom_fields, created_at, updated_at, widerrufen_at, widerruf_grund
`

type CreateDealParams struct {
	Title        string             `json:"title"`
	CompanyID    pgtype.UUID        `json:"company_id"`
	ContactID    pgtype.UUID        `json:"contact_id"`
	Value        pgtype.Numeric     `json:"value"`
	Currency     string             `json:"currency"`
	Stage        string             `json:"stage"`
	Probability  int32              `json:"probability"`
	AssignedTo   pgtype.UUID        `json:"assigned_to"`
	ClosedAt     pgtype.Timestamptz `json:"closed_at"`
	CustomFields []byte             `json:"custom_fields"`
}

// internal/db/queries/deals.sql
func (q *Queries) CreateDeal(ctx context.Context, arg CreateDealParams) (Deal, error) {
	row := q.db.QueryRow(ctx, createDeal,
		arg.Title,
		arg.CompanyID,
		arg.ContactID,
		arg.Value,
		arg.Currency,
		arg.Stage,
		arg.Probability,
		arg.AssignedTo,
		arg.ClosedAt,
		arg.CustomFields,
	)
	var i Deal
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.CompanyID,
		&i.ContactID,
		&i.Value,
		&i.Currency,
		&i.Stage,
		&i.Probability,
		&i.AssignedTo,
		&i.ClosedAt,
		&i.CustomFields,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WiderrufenAt,
		&i.WiderrufGrund,
	)
	return i, err
}

const deleteDeal = `-- name: DeleteDeal :exec
DELETE FROM deals
WHERE id = $1
`

func (q *Queries) DeleteDeal(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteDeal, id)
	return err
}

const getDealByID = `-- name: GetDealByID :one
SELECT id, title, company_id, contact_id, value, currency, stage, probability, assigned_to, closed_at, custom_fields, created_at, updated_at, widerrufen_at, widerruf_grund FROM deals
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetDealByID(ctx context.Context, id pgtype.UUID) (Deal, error) {
	row := q.db.QueryRow(ctx, getDealByID, id)
	var i Deal
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.CompanyID,
		&i.ContactID,
		&i.Value,
		&i.Currency,
		&i.Stage,
		&i.Probability,
		&i.AssignedTo,
		&i.ClosedAt,
		&i.CustomFields,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WiderrufenAt,
		&i.WiderrufGrund,
	)
	return i, err
}

const listDeals = `-- name: ListDeals :many
SELECT id, title, company_id, contact_id, value, currency, stage, probability, assigned_to, closed_at, custom_fields, created_at, updated_at, widerrufen_at, widerruf_grund FROM deals
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListDealsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListDeals(ctx context.Context, arg ListDealsParams) ([]Deal, error) {
	rows, err := q.db.Query(ctx, listDeals, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Deal
	for rows.Next() {
		var i Deal
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.CompanyID,
			&i.ContactID,
			&i.Value,
			&i.Currency,
			&i.Stage,
			&i.Probability,
			&i.AssignedTo,
			&i.ClosedAt,
			&i.CustomFields,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.WiderrufenAt,
			&i.WiderrufGrund,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDealsByStage = `-- name: ListDealsByStage :many
SELECT id, title, company_id, contact_id, value, currency, stage, probability, assigned_to, closed_at, custom_fields, created_at, updated_at, widerrufen_at, widerruf_grund FROM deals
WHERE stage = $1
ORDER BY created_at DESC
`

func (q *Queries) ListDealsByStage(ctx context.Context, stage string) ([]Deal, error) {
	rows, err := q.db.Query(ctx, listDealsByStage, stage)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Deal
	for rows.Next() {
		var i Deal
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.CompanyID,
			&i.ContactID,
			&i.Value,
			&i.Currency,
			&i.Stage,
			&i.Probability,
			&i.AssignedTo,
			&i.ClosedAt,
			&i.CustomFields,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.WiderrufenAt,
			&i.WiderrufGrund,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDeal = `-- name: UpdateDeal :one
UPDATE deals
SET title = $2,
    company_id = $3,
    contact_id = $4,
    value = $5,
    currency = $6,
    stage = $7,
    probability = $8,
    assigned_to = $9,
    closed_at = $10,
    custom_fields = $11,
    updated_at = NOW()
WHERE id = $1
RETURNING id, title, company_id, contact_id, value, currency, stage, probability, assigned_to, closed_at, custom_fields, created_at, updated_at, widerrufen_at, widerruf_grund
`

type UpdateDealParams struct {
	ID           pgtype.UUID        `json:"id"`
	Title        string             `json:"title"`
	CompanyID    pgtype.UUID        `json:"company_id"`
	ContactID    pgtype.UUID        `json:"contact_id"`
	Value        pgtype.Numeric     `json:"value"`
	Currency     string             `json:"currency"`
	Stage        string             `json:"stage"`
	Probability  int32              `json:"probability"`
	AssignedTo   pgtype.UUID        `json:"assigned_to"`
	ClosedAt     pgtype.Timestamptz `json:"closed_at"`
	CustomFields []byte             `json:"custom_fields"`
}

func (q *Queries) UpdateDeal(ctx context.Context, arg UpdateDealParams) (Deal, error) {
	row := q.db.QueryRow(ctx, updateDeal,
		arg.ID,
		arg.Title,
		arg.CompanyID,
		arg.ContactID,
		arg.Value,
		arg.Currency,
		arg.Stage,
		arg.Probability,
		arg.AssignedTo,
		arg.ClosedAt,
		arg.CustomFields,
	)
	var i Deal
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.CompanyID,
		&i.ContactID,
		&i.Value,
		&i.Currency,
		&i.Stage,
		&i.Probability,
		&i.AssignedTo,
		&i.ClosedAt,
		&i.CustomFields,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WiderrufenAt,
		&i.WiderrufGrund,
	)
	return i, err
}

const updateDealStage = `-- name: UpdateDealStage :one
UPDATE deals
SET stage = $2,
    probability = $3,
    closed_at = $4,
    updated_at = NOW()
WHERE id = $1
RETURNING id, title, company_id, contact_id, value, currency, stage, probability, assigned_to, closed_at, custom_fields, created_at, updated_at, widerrufen_at, widerruf_grund
`

type UpdateDealStageParams struct {
	ID          pgtype.UUID        `json:"id"`
	Stage       string             `json:"stage"`
	Probability int32              `json:"probability"`
	ClosedAt    pgtype.Timestamptz `json:"closed_at"`
}

func (q *Queries) UpdateDealStage(ctx context.Context, arg UpdateDealStageParams) (Deal, error) {
	row := q.db.QueryRow(ctx, updateDealStage,
		arg.ID,
		arg.Stage,
		arg.Probability,
		arg.ClosedAt,
	)
	var i Deal
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.CompanyID,
		&i.ContactID,
		&i.Value,
		&i.Currency,
		&i.Stage,
		&i.Probability,
		&i.AssignedTo,
		&i.ClosedAt,
		&i.CustomFields,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WiderrufenAt,
		&i.WiderrufGrund,
	)
	return i, err
}
