// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: emails.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEmailAccount = `-- name: CreateEmailAccount :one
INSERT INTO email_accounts (
    name,
    email_address,
    provider,
    imap_host,
    imap_port,
    smtp_host,
    smtp_port,
    username,
    password_encrypted,
    is_active,
    account_type,
    owner_user_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
RETURNING id, name, email_address, provider, imap_host, imap_port, smtp_host, smtp_port, username, password_encrypted, is_active, last_synced_at, created_at, updated_at, account_type, owner_user_id, last_sync_at, last_uid
`

type CreateEmailAccountParams struct {
	Name              string      `json:"name"`
	EmailAddress      string      `json:"email_address"`
	Provider          string      `json:"provider"`
	ImapHost          pgtype.Text `json:"imap_host"`
	ImapPort          pgtype.Int4 `json:"imap_port"`
	SmtpHost          pgtype.Text `json:"smtp_host"`
	SmtpPort          pgtype.Int4 `json:"smtp_port"`
	Username          pgtype.Text `json:"username"`
	PasswordEncrypted pgtype.Text `json:"password_encrypted"`
	IsActive          bool        `json:"is_active"`
	AccountType       string      `json:"account_type"`
	OwnerUserID       pgtype.UUID `json:"owner_user_id"`
}

// internal/db/queries/emails.sql
func (q *Queries) CreateEmailAccount(ctx context.Context, arg CreateEmailAccountParams) (EmailAccount, error) {
	row := q.db.QueryRow(ctx, createEmailAccount,
		arg.Name,
		arg.EmailAddress,
		arg.Provider,
		arg.ImapHost,
		arg.ImapPort,
		arg.SmtpHost,
		arg.SmtpPort,
		arg.Username,
		arg.PasswordEncrypted,
		arg.IsActive,
		arg.AccountType,
		arg.OwnerUserID,
	)
	var i EmailAccount
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.EmailAddress,
		&i.Provider,
		&i.ImapHost,
		&i.ImapPort,
		&i.SmtpHost,
		&i.SmtpPort,
		&i.Username,
		&i.PasswordEncrypted,
		&i.IsActive,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AccountType,
		&i.OwnerUserID,
		&i.LastSyncAt,
		&i.LastUid,
	)
	return i, err
}

const createEmailAttachment = `-- name: CreateEmailAttachment :one
INSERT INTO email_attachments (
    message_id,
    filename,
    content_type,
    size_bytes,
    storage_path
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, message_id, filename, content_type, size_bytes, storage_path, created_at
`

type CreateEmailAttachmentParams struct {
	MessageID   pgtype.UUID `json:"message_id"`
	Filename    string      `json:"filename"`
	ContentType string      `json:"content_type"`
	SizeBytes   int64       `json:"size_bytes"`
	StoragePath string      `json:"storage_path"`
}

func (q *Queries) CreateEmailAttachment(ctx context.Context, arg CreateEmailAttachmentParams) (EmailAttachment, error) {
	row := q.db.QueryRow(ctx, createEmailAttachment,
		arg.MessageID,
		arg.Filename,
		arg.ContentType,
		arg.SizeBytes,
		arg.StoragePath,
	)
	var i EmailAttachment
	err := row.Scan(
		&i.ID,
		&i.MessageID,
		&i.Filename,
		&i.ContentType,
		&i.SizeBytes,
		&i.StoragePath,
		&i.CreatedAt,
	)
	return i, err
}

const createEmailMessage = `-- name: CreateEmailMessage :one
INSERT INTO email_messages (
    account_id,
    thread_id,
    message_id,
    in_reply_to,
    direction,
    sender_email,
    sender_name,
    recipient_emails,
    subject,
    body_text,
    body_html,
    received_at,
    is_read,
    contact_id,
    deal_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15
)
RETURNING id, account_id, thread_id, message_id, in_reply_to, direction, sender_email, sender_name, recipient_emails, subject, body_text, body_html, received_at, is_read, contact_id, deal_id, created_at, tags
`

type CreateEmailMessageParams struct {
	AccountID       pgtype.UUID        `json:"account_id"`
	ThreadID        string             `json:"thread_id"`
	MessageID       string             `json:"message_id"`
	InReplyTo       pgtype.Text        `json:"in_reply_to"`
	Direction       string             `json:"direction"`
	SenderEmail     string             `json:"sender_email"`
	SenderName      pgtype.Text        `json:"sender_name"`
	RecipientEmails []byte             `json:"recipient_emails"`
	Subject         string             `json:"subject"`
	BodyText        pgtype.Text        `json:"body_text"`
	BodyHtml        pgtype.Text        `json:"body_html"`
	ReceivedAt      pgtype.Timestamptz `json:"received_at"`
	IsRead          bool               `json:"is_read"`
	ContactID       pgtype.UUID        `json:"contact_id"`
	DealID          pgtype.UUID        `json:"deal_id"`
}

func (q *Queries) CreateEmailMessage(ctx context.Context, arg CreateEmailMessageParams) (EmailMessage, error) {
	row := q.db.QueryRow(ctx, createEmailMessage,
		arg.AccountID,
		arg.ThreadID,
		arg.MessageID,
		arg.InReplyTo,
		arg.Direction,
		arg.SenderEmail,
		arg.SenderName,
		arg.RecipientEmails,
		arg.Subject,
		arg.BodyText,
		arg.BodyHtml,
		arg.ReceivedAt,
		arg.IsRead,
		arg.ContactID,
		arg.DealID,
	)
	var i EmailMessage
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.ThreadID,
		&i.MessageID,
		&i.InReplyTo,
		&i.Direction,
		&i.SenderEmail,
		&i.SenderName,
		&i.RecipientEmails,
		&i.Subject,
		&i.BodyText,
		&i.BodyHtml,
		&i.ReceivedAt,
		&i.IsRead,
		&i.ContactID,
		&i.DealID,
		&i.CreatedAt,
		&i.Tags,
	)
	return i, err
}

const deleteEmailAccount = `-- name: DeleteEmailAccount :exec
DELETE FROM email_accounts
WHERE id = $1
`

func (q *Queries) DeleteEmailAccount(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteEmailAccount, id)
	return err
}

const getEmailAccountByID = `-- name: GetEmailAccountByID :one
SELECT id, name, email_address, provider, imap_host, imap_port, smtp_host, smtp_port, username, password_encrypted, is_active, last_synced_at, created_at, updated_at, account_type, owner_user_id, last_sync_at, last_uid FROM email_accounts
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetEmailAccountByID(ctx context.Context, id pgtype.UUID) (EmailAccount, error) {
	row := q.db.QueryRow(ctx, getEmailAccountByID, id)
	var i EmailAccount
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.EmailAddress,
		&i.Provider,
		&i.ImapHost,
		&i.ImapPort,
		&i.SmtpHost,
		&i.SmtpPort,
		&i.Username,
		&i.PasswordEncrypted,
		&i.IsActive,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AccountType,
		&i.OwnerUserID,
		&i.LastSyncAt,
		&i.LastUid,
	)
	return i, err
}

const getEmailMessageByID = `-- name: GetEmailMessageByID :one
SELECT id, account_id, thread_id, message_id, in_reply_to, direction, sender_email, sender_name, recipient_emails, subject, body_text, body_html, received_at, is_read, contact_id, deal_id, created_at, tags FROM email_messages
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetEmailMessageByID(ctx context.Context, id pgtype.UUID) (EmailMessage, error) {
	row := q.db.QueryRow(ctx, getEmailMessageByID, id)
	var i EmailMessage
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.ThreadID,
		&i.MessageID,
		&i.InReplyTo,
		&i.Direction,
		&i.SenderEmail,
		&i.SenderName,
		&i.RecipientEmails,
		&i.Subject,
		&i.BodyText,
		&i.BodyHtml,
		&i.ReceivedAt,
		&i.IsRead,
		&i.ContactID,
		&i.DealID,
		&i.CreatedAt,
		&i.Tags,
	)
	return i, err
}

const listEmailAccounts = `-- name: ListEmailAccounts :many
SELECT id, name, email_address, provider, imap_host, imap_port, smtp_host, smtp_port, username, password_encrypted, is_active, last_synced_at, created_at, updated_at, account_type, owner_user_id, last_sync_at, last_uid FROM email_accounts
WHERE is_active = TRUE
ORDER BY name ASC
`

func (q *Queries) ListEmailAccounts(ctx context.Context) ([]EmailAccount, error) {
	rows, err := q.db.Query(ctx, listEmailAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EmailAccount
	for rows.Next() {
		var i EmailAccount
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.EmailAddress,
			&i.Provider,
			&i.ImapHost,
			&i.ImapPort,
			&i.SmtpHost,
			&i.SmtpPort,
			&i.Username,
			&i.PasswordEncrypted,
			&i.IsActive,
			&i.LastSyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AccountType,
			&i.OwnerUserID,
			&i.LastSyncAt,
			&i.LastUid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmailAttachmentsByMessage = `-- name: ListEmailAttachmentsByMessage :many
SELECT id, message_id, filename, content_type, size_bytes, storage_path, created_at FROM email_attachments
WHERE message_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListEmailAttachmentsByMessage(ctx context.Context, messageID pgtype.UUID) ([]EmailAttachment, error) {
	rows, err := q.db.Query(ctx, listEmailAttachmentsByMessage, messageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EmailAttachment
	for rows.Next() {
		var i EmailAttachment
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.Filename,
			&i.ContentType,
			&i.SizeBytes,
			&i.StoragePath,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmailMessages = `-- name: ListEmailMessages :many
SELECT id, account_id, thread_id, message_id, in_reply_to, direction, sender_email, sender_name, recipient_emails, subject, body_text, body_html, received_at, is_read, contact_id, deal_id, created_at, tags FROM email_messages
ORDER BY received_at DESC
LIMIT $1 OFFSET $2
`

type ListEmailMessagesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListEmailMessages(ctx context.Context, arg ListEmailMessagesParams) ([]EmailMessage, error) {
	rows, err := q.db.Query(ctx, listEmailMessages, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EmailMessage
	for rows.Next() {
		var i EmailMessage
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.ThreadID,
			&i.MessageID,
			&i.InReplyTo,
			&i.Direction,
			&i.SenderEmail,
			&i.SenderName,
			&i.RecipientEmails,
			&i.Subject,
			&i.BodyText,
			&i.BodyHtml,
			&i.ReceivedAt,
			&i.IsRead,
			&i.ContactID,
			&i.DealID,
			&i.CreatedAt,
			&i.Tags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmailMessagesByThread = `-- name: ListEmailMessagesByThread :many
SELECT id, account_id, thread_id, message_id, in_reply_to, direction, sender_email, sender_name, recipient_emails, subject, body_text, body_html, received_at, is_read, contact_id, deal_id, created_at, tags FROM email_messages
WHERE thread_id = $1
ORDER BY received_at ASC
`

func (q *Queries) ListEmailMessagesByThread(ctx context.Context, threadID string) ([]EmailMessage, error) {
	rows, err := q.db.Query(ctx, listEmailMessagesByThread, threadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EmailMessage
	for rows.Next() {
		var i EmailMessage
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.ThreadID,
			&i.MessageID,
			&i.InReplyTo,
			&i.Direction,
			&i.SenderEmail,
			&i.SenderName,
			&i.RecipientEmails,
			&i.Subject,
			&i.BodyText,
			&i.BodyHtml,
			&i.ReceivedAt,
			&i.IsRead,
			&i.ContactID,
			&i.DealID,
			&i.CreatedAt,
			&i.Tags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markEmailMessageRead = `-- name: MarkEmailMessageRead :exec
UPDATE email_messages
SET is_read = TRUE
WHERE id = $1
`

func (q *Queries) MarkEmailMessageRead(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markEmailMessageRead, id)
	return err
}

const updateEmailAccount = `-- name: UpdateEmailAccount :one
UPDATE email_accounts
SET name = $2,
    imap_host = $3,
    imap_port = $4,
    smtp_host = $5,
    smtp_port = $6,
    username = $7,
    password_encrypted = $8,
    is_active = $9,
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, email_address, provider, imap_host, imap_port, smtp_host, smtp_port, username, password_encrypted, is_active, last_synced_at, created_at, updated_at, account_type, owner_user_id, last_sync_at, last_uid
`

type UpdateEmailAccountParams struct {
	ID                pgtype.UUID `json:"id"`
	Name              string      `json:"name"`
	ImapHost          pgtype.Text `json:"imap_host"`
	ImapPort          pgtype.Int4 `json:"imap_port"`
	SmtpHost          pgtype.Text `json:"smtp_host"`
	SmtpPort          pgtype.Int4 `json:"smtp_port"`
	Username          pgtype.Text `json:"username"`
	PasswordEncrypted pgtype.Text `json:"password_encrypted"`
	IsActive          bool        `json:"is_active"`
}

func (q *Queries) UpdateEmailAccount(ctx context.Context, arg UpdateEmailAccountParams) (EmailAccount, error) {
	row := q.db.QueryRow(ctx, updateEmailAccount,
		arg.ID,
		arg.Name,
		arg.ImapHost,
		arg.ImapPort,
		arg.SmtpHost,
		arg.SmtpPort,
		arg.Username,
		arg.PasswordEncrypted,
		arg.IsActive,
	)
	var i EmailAccount
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.EmailAddress,
		&i.Provider,
		&i.ImapHost,
		&i.ImapPort,
		&i.SmtpHost,
		&i.SmtpPort,
		&i.Username,
		&i.PasswordEncrypted,
		&i.IsActive,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AccountType,
		&i.OwnerUserID,
		&i.LastSyncAt,
		&i.LastUid,
	)
	return i, err
}

const updateEmailAccountLastSynced = `-- name: UpdateEmailAccountLastSynced :exec
UPDATE email_accounts
SET last_synced_at = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateEmailAccountLastSyncedParams struct {
	ID           pgtype.UUID        `json:"id"`
	LastSyncedAt pgtype.Timestamptz `json:"last_synced_at"`
}

func (q *Queries) UpdateEmailAccountLastSynced(ctx context.Context, arg UpdateEmailAccountLastSyncedParams) error {
	_, err := q.db.Exec(ctx, updateEmailAccountLastSynced, arg.ID, arg.LastSyncedAt)
	return err
}

const updateEmailAccountSyncState = `-- name: UpdateEmailAccountSyncState :exec
UPDATE email_accounts
SET last_sync_at = $2, last_uid = $3, last_synced_at = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateEmailAccountSyncStateParams struct {
	ID         pgtype.UUID        `json:"id"`
	LastSyncAt pgtype.Timestamptz `json:"last_sync_at"`
	LastUid    int64              `json:"last_uid"`
}

func (q *Queries) UpdateEmailAccountSyncState(ctx context.Context, arg UpdateEmailAccountSyncStateParams) error {
	_, err := q.db.Exec(ctx, updateEmailAccountSyncState, arg.ID, arg.LastSyncAt, arg.LastUid)
	return err
}

const updateEmailMessageTags = `-- name: UpdateEmailMessageTags :one
UPDATE email_messages
SET tags = $2
WHERE id = $1
RETURNING id, account_id, thread_id, message_id, in_reply_to, direction, sender_email, sender_name, recipient_emails, subject, body_text, body_html, received_at, is_read, contact_id, deal_id, created_at, tags
`

type UpdateEmailMessageTagsParams struct {
	ID   pgtype.UUID     `json:"id"`
	Tags json.RawMessage `json:"tags"`
}

func (q *Queries) UpdateEmailMessageTags(ctx context.Context, arg UpdateEmailMessageTagsParams) (EmailMessage, error) {
	row := q.db.QueryRow(ctx, updateEmailMessageTags, arg.ID, arg.Tags)
	var i EmailMessage
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.ThreadID,
		&i.MessageID,
		&i.InReplyTo,
		&i.Direction,
		&i.SenderEmail,
		&i.SenderName,
		&i.RecipientEmails,
		&i.Subject,
		&i.BodyText,
		&i.BodyHtml,
		&i.ReceivedAt,
		&i.IsRead,
		&i.ContactID,
		&i.DealID,
		&i.CreatedAt,
		&i.Tags,
	)
	return i, err
}
