// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: knowledge_base.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createKBArticle = `-- name: CreateKBArticle :one

INSERT INTO knowledge_base_articles (
    title,
    category,
    content,
    tags,
    author,
    embedding,
    embedding_model
) VALUES (
    $1, $2, $3, $4, $5, $6::vector, $7
)
RETURNING id, title, category, content, tags, author, embedding_model,
    (embedding IS NOT NULL)::boolean AS indexed, created_at, updated_at
`

type CreateKBArticleParams struct {
	Title          string      `json:"title"`
	Category       string      `json:"category"`
	Content        string      `json:"content"`
	Tags           []string    `json:"tags"`
	Author         string      `json:"author"`
	Embedding      string      `json:"embedding"`
	EmbeddingModel pgtype.Text `json:"embedding_model"`
}

type CreateKBArticleRow struct {
	ID             pgtype.UUID        `json:"id"`
	Title          string             `json:"title"`
	Category       string             `json:"category"`
	Content        string             `json:"content"`
	Tags           []string           `json:"tags"`
	Author         string             `json:"author"`
	EmbeddingModel pgtype.Text        `json:"embedding_model"`
	Indexed        bool               `json:"indexed"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

// internal/db/queries/knowledge_base.sql
func (q *Queries) CreateKBArticle(ctx context.Context, arg CreateKBArticleParams) (CreateKBArticleRow, error) {
	row := q.db.QueryRow(ctx, createKBArticle,
		arg.Title,
		arg.Category,
		arg.Content,
		arg.Tags,
		arg.Author,
		arg.Embedding,
		arg.EmbeddingModel,
	)
	var i CreateKBArticleRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Category,
		&i.Content,
		&i.Tags,
		&i.Author,
		&i.EmbeddingModel,
		&i.Indexed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteKBArticle = `-- name: DeleteKBArticle :exec
DELETE FROM knowledge_base_articles
WHERE id = $1
`

func (q *Queries) DeleteKBArticle(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteKBArticle, id)
	return err
}

const getKBArticleByID = `-- name: GetKBArticleByID :one
SELECT id, title, category, content, tags, author, embedding_model,
    (embedding IS NOT NULL)::boolean AS indexed, created_at, updated_at
FROM knowledge_base_articles
WHERE id = $1 LIMIT 1
`

type GetKBArticleByIDRow struct {
	ID             pgtype.UUID        `json:"id"`
	Title          string             `json:"title"`
	Category       string             `json:"category"`
	Content        string             `json:"content"`
	Tags           []string           `json:"tags"`
	Author         string             `json:"author"`
	EmbeddingModel pgtype.Text        `json:"embedding_model"`
	Indexed        bool               `json:"indexed"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetKBArticleByID(ctx context.Context, id pgtype.UUID) (GetKBArticleByIDRow, error) {
	row := q.db.QueryRow(ctx, getKBArticleByID, id)
	var i GetKBArticleByIDRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Category,
		&i.Content,
		&i.Tags,
		&i.Author,
		&i.EmbeddingModel,
		&i.Indexed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listKBArticles = `-- name: ListKBArticles :many
SELECT id, title, category, content, tags, author, embedding_model,
    (embedding IS NOT NULL)::boolean AS indexed, created_at, updated_at
FROM knowledge_base_articles
ORDER BY created_at DESC
`

type ListKBArticlesRow struct {
	ID             pgtype.UUID        `json:"id"`
	Title          string             `json:"title"`
	Category       string             `json:"category"`
	Content        string             `json:"content"`
	Tags           []string           `json:"tags"`
	Author         string             `json:"author"`
	EmbeddingModel pgtype.Text        `json:"embedding_model"`
	Indexed        bool               `json:"indexed"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListKBArticles(ctx context.Context) ([]ListKBArticlesRow, error) {
	rows, err := q.db.Query(ctx, listKBArticles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListKBArticlesRow
	for rows.Next() {
		var i ListKBArticlesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Category,
			&i.Content,
			&i.Tags,
			&i.Author,
			&i.EmbeddingModel,
			&i.Indexed,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchKBArticlesByEmbedding = `-- name: SearchKBArticlesByEmbedding :many
SELECT id, title, category, content, tags, author, embedding_model,
    (embedding IS NOT NULL)::boolean AS indexed, created_at, updated_at,
    (embedding <=> $1::vector)::float8 AS distance
FROM knowledge_base_articles
WHERE embedding IS NOT NULL
ORDER BY embedding <=> $1::vector
LIMIT $2
`

type SearchKBArticlesByEmbeddingParams struct {
	Embedding  string `json:"embedding"`
	LimitCount int32  `json:"limit_count"`
}

type SearchKBArticlesByEmbeddingRow struct {
	ID             pgtype.UUID        `json:"id"`
	Title          string             `json:"title"`
	Category       string             `json:"category"`
	Content        string             `json:"content"`
	Tags           []string           `json:"tags"`
	Author         string             `json:"author"`
	EmbeddingModel pgtype.Text        `json:"embedding_model"`
	Indexed        bool               `json:"indexed"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	Distance       float64            `json:"distance"`
}

func (q *Queries) SearchKBArticlesByEmbedding(ctx context.Context, arg SearchKBArticlesByEmbeddingParams) ([]SearchKBArticlesByEmbeddingRow, error) {
	rows, err := q.db.Query(ctx, searchKBArticlesByEmbedding, arg.Embedding, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchKBArticlesByEmbeddingRow
	for rows.Next() {
		var i SearchKBArticlesByEmbeddingRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Category,
			&i.Content,
			&i.Tags,
			&i.Author,
			&i.EmbeddingModel,
			&i.Indexed,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Distance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateKBArticleEmbedding = `-- name: UpdateKBArticleEmbedding :exec
UPDATE knowledge_base_articles
SET embedding = $1::vector, embedding_model = $2
WHERE id = $3
`

type UpdateKBArticleEmbeddingParams struct {
	Embedding      string      `json:"embedding"`
	EmbeddingModel pgtype.Text `json:"embedding_model"`
	ID             pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateKBArticleEmbedding(ctx context.Context, arg UpdateKBArticleEmbeddingParams) error {
	_, err := q.db.Exec(ctx, updateKBArticleEmbedding, arg.Embedding, arg.EmbeddingModel, arg.ID)
	return err
}
