// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: knowledge_base.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createKBArticle = `-- name: CreateKBArticle :one

INSERT INTO knowledge_base_articles (
    title,
    category,
    content,
    tags,
    author
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, title, category, content, tags, author, created_at, updated_at
`

type CreateKBArticleParams struct {
	Title    string   `json:"title"`
	Category string   `json:"category"`
	Content  string   `json:"content"`
	Tags     []string `json:"tags"`
	Author   string   `json:"author"`
}

// internal/db/queries/knowledge_base.sql
func (q *Queries) CreateKBArticle(ctx context.Context, arg CreateKBArticleParams) (KnowledgeBaseArticle, error) {
	row := q.db.QueryRow(ctx, createKBArticle,
		arg.Title,
		arg.Category,
		arg.Content,
		arg.Tags,
		arg.Author,
	)
	var i KnowledgeBaseArticle
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Category,
		&i.Content,
		&i.Tags,
		&i.Author,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteKBArticle = `-- name: DeleteKBArticle :exec
DELETE FROM knowledge_base_articles
WHERE id = $1
`

func (q *Queries) DeleteKBArticle(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteKBArticle, id)
	return err
}

const getKBArticleByID = `-- name: GetKBArticleByID :one
SELECT id, title, category, content, tags, author, created_at, updated_at FROM knowledge_base_articles
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetKBArticleByID(ctx context.Context, id pgtype.UUID) (KnowledgeBaseArticle, error) {
	row := q.db.QueryRow(ctx, getKBArticleByID, id)
	var i KnowledgeBaseArticle
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Category,
		&i.Content,
		&i.Tags,
		&i.Author,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listKBArticles = `-- name: ListKBArticles :many
SELECT id, title, category, content, tags, author, created_at, updated_at FROM knowledge_base_articles
ORDER BY created_at DESC
`

func (q *Queries) ListKBArticles(ctx context.Context) ([]KnowledgeBaseArticle, error) {
	rows, err := q.db.Query(ctx, listKBArticles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []KnowledgeBaseArticle
	for rows.Next() {
		var i KnowledgeBaseArticle
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Category,
			&i.Content,
			&i.Tags,
			&i.Author,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
