// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	EntityType string             `json:"entity_type"`
	EntityID   pgtype.UUID        `json:"entity_id"`
	Action     string             `json:"action"`
	Changes    []byte             `json:"changes"`
	IpAddress  pgtype.Text        `json:"ip_address"`
	UserAgent  pgtype.Text        `json:"user_agent"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Company struct {
	ID             pgtype.UUID        `json:"id"`
	Name           string             `json:"name"`
	Domain         pgtype.Text        `json:"domain"`
	Phone          pgtype.Text        `json:"phone"`
	Email          pgtype.Text        `json:"email"`
	AddressStreet  pgtype.Text        `json:"address_street"`
	AddressZip     pgtype.Text        `json:"address_zip"`
	AddressCity    pgtype.Text        `json:"address_city"`
	AddressCountry pgtype.Text        `json:"address_country"`
	CustomFields   []byte             `json:"custom_fields"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Contact struct {
	ID                pgtype.UUID        `json:"id"`
	CompanyID         pgtype.UUID        `json:"company_id"`
	FirstName         string             `json:"first_name"`
	LastName          string             `json:"last_name"`
	Email             pgtype.Text        `json:"email"`
	Phone             pgtype.Text        `json:"phone"`
	Mobile            pgtype.Text        `json:"mobile"`
	Position          pgtype.Text        `json:"position"`
	LeadSource        pgtype.Text        `json:"lead_source"`
	AddressStreet     pgtype.Text        `json:"address_street"`
	AddressZip        pgtype.Text        `json:"address_zip"`
	AddressCity       pgtype.Text        `json:"address_city"`
	Latitude          pgtype.Float8      `json:"latitude"`
	Longitude         pgtype.Float8      `json:"longitude"`
	CustomFields      []byte             `json:"custom_fields"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	ConsentPhone      bool               `json:"consent_phone"`
	ConsentEmail      bool               `json:"consent_email"`
	ConsentUpdatedAt  pgtype.Timestamptz `json:"consent_updated_at"`
	StromverbrauchKwh pgtype.Numeric     `json:"stromverbrauch_kwh"`
	GasverbrauchKwh   pgtype.Numeric     `json:"gasverbrauch_kwh"`
	Zaehlernummer     pgtype.Text        `json:"zaehlernummer"`
	EigentuemerStatus pgtype.Text        `json:"eigentuemer_status"`
}

type Deal struct {
	ID            pgtype.UUID        `json:"id"`
	Title         string             `json:"title"`
	CompanyID     pgtype.UUID        `json:"company_id"`
	ContactID     pgtype.UUID        `json:"contact_id"`
	Value         pgtype.Numeric     `json:"value"`
	Currency      string             `json:"currency"`
	Stage         string             `json:"stage"`
	Probability   int32              `json:"probability"`
	AssignedTo    pgtype.UUID        `json:"assigned_to"`
	ClosedAt      pgtype.Timestamptz `json:"closed_at"`
	CustomFields  []byte             `json:"custom_fields"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	WiderrufenAt  pgtype.Timestamptz `json:"widerrufen_at"`
	WiderrufGrund pgtype.Text        `json:"widerruf_grund"`
}

type EmailAccount struct {
	ID                pgtype.UUID        `json:"id"`
	Name              string             `json:"name"`
	EmailAddress      string             `json:"email_address"`
	Provider          string             `json:"provider"`
	ImapHost          pgtype.Text        `json:"imap_host"`
	ImapPort          pgtype.Int4        `json:"imap_port"`
	SmtpHost          pgtype.Text        `json:"smtp_host"`
	SmtpPort          pgtype.Int4        `json:"smtp_port"`
	Username          pgtype.Text        `json:"username"`
	PasswordEncrypted pgtype.Text        `json:"password_encrypted"`
	IsActive          bool               `json:"is_active"`
	LastSyncedAt      pgtype.Timestamptz `json:"last_synced_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type EmailAttachment struct {
	ID          pgtype.UUID        `json:"id"`
	MessageID   pgtype.UUID        `json:"message_id"`
	Filename    string             `json:"filename"`
	ContentType string             `json:"content_type"`
	SizeBytes   int64              `json:"size_bytes"`
	StoragePath string             `json:"storage_path"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type EmailMessage struct {
	ID              pgtype.UUID        `json:"id"`
	AccountID       pgtype.UUID        `json:"account_id"`
	ThreadID        string             `json:"thread_id"`
	MessageID       string             `json:"message_id"`
	InReplyTo       pgtype.Text        `json:"in_reply_to"`
	Direction       string             `json:"direction"`
	SenderEmail     string             `json:"sender_email"`
	SenderName      pgtype.Text        `json:"sender_name"`
	RecipientEmails []byte             `json:"recipient_emails"`
	Subject         string             `json:"subject"`
	BodyText        pgtype.Text        `json:"body_text"`
	BodyHtml        pgtype.Text        `json:"body_html"`
	ReceivedAt      pgtype.Timestamptz `json:"received_at"`
	IsRead          bool               `json:"is_read"`
	ContactID       pgtype.UUID        `json:"contact_id"`
	DealID          pgtype.UUID        `json:"deal_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type Notification struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Type      string             `json:"type"`
	Title     string             `json:"title"`
	Message   string             `json:"message"`
	Link      pgtype.Text        `json:"link"`
	IsRead    bool               `json:"is_read"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type RefreshToken struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	UserAgent pgtype.Text        `json:"user_agent"`
	IpAddress pgtype.Text        `json:"ip_address"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Todo struct {
	ID          pgtype.UUID        `json:"id"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	DueDate     pgtype.Timestamptz `json:"due_date"`
	Status      string             `json:"status"`
	Priority    string             `json:"priority"`
	AssignedTo  pgtype.UUID        `json:"assigned_to"`
	ContactID   pgtype.UUID        `json:"contact_id"`
	DealID      pgtype.UUID        `json:"deal_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID                  pgtype.UUID        `json:"id"`
	Email               string             `json:"email"`
	PasswordHash        string             `json:"password_hash"`
	FirstName           string             `json:"first_name"`
	LastName            string             `json:"last_name"`
	Role                string             `json:"role"`
	Status              string             `json:"status"`
	TotpSecretEncrypted pgtype.Text        `json:"totp_secret_encrypted"`
	TotpEnabled         bool               `json:"totp_enabled"`
	LastLoginAt         pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}
