// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type UserRole string

const (
	UserRoleADMIN      UserRole = "ADMIN"
	UserRoleBENUTZER   UserRole = "BENUTZER"
	UserRoleVERTRIEB   UserRole = "VERTRIEB"
	UserRoleBACKOFFICE UserRole = "BACKOFFICE"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type UserStatus string

const (
	UserStatusACTIVE      UserStatus = "ACTIVE"
	UserStatusINVITED     UserStatus = "INVITED"
	UserStatusDEACTIVATED UserStatus = "DEACTIVATED"
)

func (e *UserStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserStatus(s)
	case string:
		*e = UserStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for UserStatus: %T", src)
	}
	return nil
}

type NullUserStatus struct {
	UserStatus UserStatus `json:"user_status"`
	Valid      bool       `json:"valid"` // Valid is true if UserStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserStatus) Scan(value interface{}) error {
	if value == nil {
		ns.UserStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserStatus), nil
}

type AiAuditLog struct {
	ID                 pgtype.UUID        `json:"id"`
	InteractionType    string             `json:"interaction_type"`
	ModelName          string             `json:"model_name"`
	Provider           string             `json:"provider"`
	PromptTokens       int32              `json:"prompt_tokens"`
	CompletionTokens   int32              `json:"completion_tokens"`
	LatencyMs          int32              `json:"latency_ms"`
	PiiFilterTriggered bool               `json:"pii_filter_triggered"`
	PiiRedactionsCount int32              `json:"pii_redactions_count"`
	HumanApproved      pgtype.Bool        `json:"human_approved"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type AiResearchJob struct {
	ID           pgtype.UUID        `json:"id"`
	CompanyName  string             `json:"company_name"`
	Domain       string             `json:"domain"`
	Status       string             `json:"status"`
	ResultJson   []byte             `json:"result_json"`
	ErrorMessage string             `json:"error_message"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	CompletedAt  pgtype.Timestamptz `json:"completed_at"`
}

type Appointment struct {
	ID         pgtype.UUID        `json:"id"`
	Title      string             `json:"title"`
	ContactID  pgtype.UUID        `json:"contact_id"`
	CompanyID  pgtype.UUID        `json:"company_id"`
	DealID     pgtype.UUID        `json:"deal_id"`
	StartTime  pgtype.Timestamptz `json:"start_time"`
	EndTime    pgtype.Timestamptz `json:"end_time"`
	Location   string             `json:"location"`
	Notes      string             `json:"notes"`
	IcsUid     string             `json:"ics_uid"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	AssignedTo string             `json:"assigned_to"`
	Type       string             `json:"type"`
	IsExternal bool               `json:"is_external"`
	Provider   string             `json:"provider"`
	IsPrivate  bool               `json:"is_private"`
	IsPushed   bool               `json:"is_pushed"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type AuditLog struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	EntityType string             `json:"entity_type"`
	EntityID   pgtype.UUID        `json:"entity_id"`
	Action     string             `json:"action"`
	Changes    []byte             `json:"changes"`
	IpAddress  pgtype.Text        `json:"ip_address"`
	UserAgent  pgtype.Text        `json:"user_agent"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type CallActivity struct {
	ID              pgtype.UUID        `json:"id"`
	ContactID       pgtype.UUID        `json:"contact_id"`
	DurationSeconds int32              `json:"duration_seconds"`
	Disposition     string             `json:"disposition"`
	Notes           string             `json:"notes"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type Company struct {
	ID             pgtype.UUID        `json:"id"`
	Name           string             `json:"name"`
	Domain         pgtype.Text        `json:"domain"`
	Phone          pgtype.Text        `json:"phone"`
	Email          pgtype.Text        `json:"email"`
	AddressStreet  pgtype.Text        `json:"address_street"`
	AddressZip     pgtype.Text        `json:"address_zip"`
	AddressCity    pgtype.Text        `json:"address_city"`
	AddressCountry pgtype.Text        `json:"address_country"`
	CustomFields   []byte             `json:"custom_fields"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type CompanyResearch struct {
	ID               pgtype.UUID        `json:"id"`
	CompanyID        pgtype.UUID        `json:"company_id"`
	Domain           string             `json:"domain"`
	Title            string             `json:"title"`
	MetaDescription  string             `json:"meta_description"`
	Summary          string             `json:"summary"`
	IndustryKeywords []string           `json:"industry_keywords"`
	ResearchedAt     pgtype.Timestamptz `json:"researched_at"`
}

type Contact struct {
	ID                pgtype.UUID        `json:"id"`
	CompanyID         pgtype.UUID        `json:"company_id"`
	FirstName         string             `json:"first_name"`
	LastName          string             `json:"last_name"`
	Email             pgtype.Text        `json:"email"`
	Phone             pgtype.Text        `json:"phone"`
	Mobile            pgtype.Text        `json:"mobile"`
	Position          pgtype.Text        `json:"position"`
	LeadSource        pgtype.Text        `json:"lead_source"`
	AddressStreet     pgtype.Text        `json:"address_street"`
	AddressZip        pgtype.Text        `json:"address_zip"`
	AddressCity       pgtype.Text        `json:"address_city"`
	Latitude          pgtype.Float8      `json:"latitude"`
	Longitude         pgtype.Float8      `json:"longitude"`
	CustomFields      []byte             `json:"custom_fields"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	ConsentPhone      bool               `json:"consent_phone"`
	ConsentEmail      bool               `json:"consent_email"`
	ConsentUpdatedAt  pgtype.Timestamptz `json:"consent_updated_at"`
	StromverbrauchKwh pgtype.Numeric     `json:"stromverbrauch_kwh"`
	GasverbrauchKwh   pgtype.Numeric     `json:"gasverbrauch_kwh"`
	Zaehlernummer     pgtype.Text        `json:"zaehlernummer"`
	EigentuemerStatus pgtype.Text        `json:"eigentuemer_status"`
}

type Deal struct {
	ID            pgtype.UUID        `json:"id"`
	Title         string             `json:"title"`
	CompanyID     pgtype.UUID        `json:"company_id"`
	ContactID     pgtype.UUID        `json:"contact_id"`
	Value         pgtype.Numeric     `json:"value"`
	Currency      string             `json:"currency"`
	Stage         string             `json:"stage"`
	Probability   int32              `json:"probability"`
	AssignedTo    pgtype.UUID        `json:"assigned_to"`
	ClosedAt      pgtype.Timestamptz `json:"closed_at"`
	CustomFields  []byte             `json:"custom_fields"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	WiderrufenAt  pgtype.Timestamptz `json:"widerrufen_at"`
	WiderrufGrund pgtype.Text        `json:"widerruf_grund"`
}

type EmailAccount struct {
	ID                pgtype.UUID        `json:"id"`
	Name              string             `json:"name"`
	EmailAddress      string             `json:"email_address"`
	Provider          string             `json:"provider"`
	ImapHost          pgtype.Text        `json:"imap_host"`
	ImapPort          pgtype.Int4        `json:"imap_port"`
	SmtpHost          pgtype.Text        `json:"smtp_host"`
	SmtpPort          pgtype.Int4        `json:"smtp_port"`
	Username          pgtype.Text        `json:"username"`
	PasswordEncrypted pgtype.Text        `json:"password_encrypted"`
	IsActive          bool               `json:"is_active"`
	LastSyncedAt      pgtype.Timestamptz `json:"last_synced_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type EmailAttachment struct {
	ID          pgtype.UUID        `json:"id"`
	MessageID   pgtype.UUID        `json:"message_id"`
	Filename    string             `json:"filename"`
	ContentType string             `json:"content_type"`
	SizeBytes   int64              `json:"size_bytes"`
	StoragePath string             `json:"storage_path"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type EmailMessage struct {
	ID              pgtype.UUID        `json:"id"`
	AccountID       pgtype.UUID        `json:"account_id"`
	ThreadID        string             `json:"thread_id"`
	MessageID       string             `json:"message_id"`
	InReplyTo       pgtype.Text        `json:"in_reply_to"`
	Direction       string             `json:"direction"`
	SenderEmail     string             `json:"sender_email"`
	SenderName      pgtype.Text        `json:"sender_name"`
	RecipientEmails []byte             `json:"recipient_emails"`
	Subject         string             `json:"subject"`
	BodyText        pgtype.Text        `json:"body_text"`
	BodyHtml        pgtype.Text        `json:"body_html"`
	ReceivedAt      pgtype.Timestamptz `json:"received_at"`
	IsRead          bool               `json:"is_read"`
	ContactID       pgtype.UUID        `json:"contact_id"`
	DealID          pgtype.UUID        `json:"deal_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type IntakeForm struct {
	ID         pgtype.UUID        `json:"id"`
	Name       string             `json:"name"`
	Slug       string             `json:"slug"`
	FieldsJson []byte             `json:"fields_json"`
	IsActive   bool               `json:"is_active"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type KnowledgeBaseArticle struct {
	ID        pgtype.UUID        `json:"id"`
	Title     string             `json:"title"`
	Category  string             `json:"category"`
	Content   string             `json:"content"`
	Tags      []string           `json:"tags"`
	Author    string             `json:"author"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Note struct {
	ID         pgtype.UUID        `json:"id"`
	EntityType string             `json:"entity_type"`
	EntityID   pgtype.UUID        `json:"entity_id"`
	Type       string             `json:"type"`
	Author     string             `json:"author"`
	Content    string             `json:"content"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type Notification struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Type      string             `json:"type"`
	Title     string             `json:"title"`
	Message   string             `json:"message"`
	Link      pgtype.Text        `json:"link"`
	IsRead    bool               `json:"is_read"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type RefreshToken struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	UserAgent pgtype.Text        `json:"user_agent"`
	IpAddress pgtype.Text        `json:"ip_address"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Todo struct {
	ID          pgtype.UUID        `json:"id"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	DueDate     pgtype.Timestamptz `json:"due_date"`
	Status      string             `json:"status"`
	Priority    string             `json:"priority"`
	AssignedTo  pgtype.UUID        `json:"assigned_to"`
	ContactID   pgtype.UUID        `json:"contact_id"`
	DealID      pgtype.UUID        `json:"deal_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID                  pgtype.UUID        `json:"id"`
	Email               string             `json:"email"`
	PasswordHash        string             `json:"password_hash"`
	FirstName           string             `json:"first_name"`
	LastName            string             `json:"last_name"`
	Role                string             `json:"role"`
	Status              string             `json:"status"`
	TotpSecretEncrypted pgtype.Text        `json:"totp_secret_encrypted"`
	TotpEnabled         bool               `json:"totp_enabled"`
	LastLoginAt         pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	TotpLastUsedStep    int64              `json:"totp_last_used_step"`
}

type Workflow struct {
	ID          string             `json:"id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	TriggerType string             `json:"trigger_type"`
	TargetType  string             `json:"target_type"`
	IsActive    bool               `json:"is_active"`
	StepsJson   []byte             `json:"steps_json"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type WorkflowRun struct {
	ID           string             `json:"id"`
	WorkflowID   string             `json:"workflow_id"`
	TargetID     string             `json:"target_id"`
	TargetType   string             `json:"target_type"`
	TargetName   string             `json:"target_name"`
	Status       string             `json:"status"`
	CurrentStep  int32              `json:"current_step"`
	SnapshotJson []byte             `json:"snapshot_json"`
	StartedAt    pgtype.Timestamptz `json:"started_at"`
	CompletedAt  pgtype.Timestamptz `json:"completed_at"`
}

type WorkflowStep struct {
	ID          string             `json:"id"`
	RunID       string             `json:"run_id"`
	StepNumber  int32              `json:"step_number"`
	Title       string             `json:"title"`
	ActionType  string             `json:"action_type"`
	PayloadJson []byte             `json:"payload_json"`
	Status      string             `json:"status"`
	PreparedAt  pgtype.Timestamptz `json:"prepared_at"`
	ExecutedAt  pgtype.Timestamptz `json:"executed_at"`
}
