// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notes.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createNote = `-- name: CreateNote :one

INSERT INTO notes (
    entity_type,
    entity_id,
    type,
    author,
    content
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, entity_type, entity_id, type, author, content, created_at, updated_at
`

type CreateNoteParams struct {
	EntityType string      `json:"entity_type"`
	EntityID   pgtype.UUID `json:"entity_id"`
	Type       string      `json:"type"`
	Author     string      `json:"author"`
	Content    string      `json:"content"`
}

// internal/db/queries/notes.sql
func (q *Queries) CreateNote(ctx context.Context, arg CreateNoteParams) (Note, error) {
	row := q.db.QueryRow(ctx, createNote,
		arg.EntityType,
		arg.EntityID,
		arg.Type,
		arg.Author,
		arg.Content,
	)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.EntityType,
		&i.EntityID,
		&i.Type,
		&i.Author,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteNote = `-- name: DeleteNote :exec
DELETE FROM notes
WHERE id = $1
`

func (q *Queries) DeleteNote(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteNote, id)
	return err
}

const getNoteByID = `-- name: GetNoteByID :one
SELECT id, entity_type, entity_id, type, author, content, created_at, updated_at FROM notes
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetNoteByID(ctx context.Context, id pgtype.UUID) (Note, error) {
	row := q.db.QueryRow(ctx, getNoteByID, id)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.EntityType,
		&i.EntityID,
		&i.Type,
		&i.Author,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listNotes = `-- name: ListNotes :many
SELECT id, entity_type, entity_id, type, author, content, created_at, updated_at FROM notes
ORDER BY created_at DESC
`

func (q *Queries) ListNotes(ctx context.Context) ([]Note, error) {
	rows, err := q.db.Query(ctx, listNotes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Note
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.EntityType,
			&i.EntityID,
			&i.Type,
			&i.Author,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotesByEntity = `-- name: ListNotesByEntity :many
SELECT id, entity_type, entity_id, type, author, content, created_at, updated_at FROM notes
WHERE entity_type = $1 AND entity_id = $2
ORDER BY created_at DESC
`

type ListNotesByEntityParams struct {
	EntityType string      `json:"entity_type"`
	EntityID   pgtype.UUID `json:"entity_id"`
}

func (q *Queries) ListNotesByEntity(ctx context.Context, arg ListNotesByEntityParams) ([]Note, error) {
	rows, err := q.db.Query(ctx, listNotesByEntity, arg.EntityType, arg.EntityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Note
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.EntityType,
			&i.EntityID,
			&i.Type,
			&i.Author,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNote = `-- name: UpdateNote :one
UPDATE notes
SET content = $2,
    type = $3,
    updated_at = NOW()
WHERE id = $1
RETURNING id, entity_type, entity_id, type, author, content, created_at, updated_at
`

type UpdateNoteParams struct {
	ID      pgtype.UUID `json:"id"`
	Content string      `json:"content"`
	Type    string      `json:"type"`
}

func (q *Queries) UpdateNote(ctx context.Context, arg UpdateNoteParams) (Note, error) {
	row := q.db.QueryRow(ctx, updateNote, arg.ID, arg.Content, arg.Type)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.EntityType,
		&i.EntityID,
		&i.Type,
		&i.Author,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
