// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (
    user_id,
    type,
    title,
    message,
    link,
    is_read
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, user_id, type, title, message, link, is_read, created_at
`

type CreateNotificationParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	Type    string      `json:"type"`
	Title   string      `json:"title"`
	Message string      `json:"message"`
	Link    pgtype.Text `json:"link"`
	IsRead  bool        `json:"is_read"`
}

// internal/db/queries/notifications.sql
func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.UserID,
		arg.Type,
		arg.Title,
		arg.Message,
		arg.Link,
		arg.IsRead,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Title,
		&i.Message,
		&i.Link,
		&i.IsRead,
		&i.CreatedAt,
	)
	return i, err
}

const listAllNotifications = `-- name: ListAllNotifications :many
SELECT id, user_id, type, title, message, link, is_read, created_at FROM notifications
WHERE (user_id = $1 OR user_id IS NULL)
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListAllNotificationsParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) ListAllNotifications(ctx context.Context, arg ListAllNotificationsParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listAllNotifications, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Title,
			&i.Message,
			&i.Link,
			&i.IsRead,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnreadNotifications = `-- name: ListUnreadNotifications :many
SELECT id, user_id, type, title, message, link, is_read, created_at FROM notifications
WHERE (user_id = $1 OR user_id IS NULL)
  AND is_read = FALSE
ORDER BY created_at DESC
LIMIT $2
`

type ListUnreadNotificationsParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
}

func (q *Queries) ListUnreadNotifications(ctx context.Context, arg ListUnreadNotificationsParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listUnreadNotifications, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Title,
			&i.Message,
			&i.Link,
			&i.IsRead,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsAsRead = `-- name: MarkAllNotificationsAsRead :exec
UPDATE notifications
SET is_read = TRUE
WHERE (user_id = $1 OR user_id IS NULL)
`

func (q *Queries) MarkAllNotificationsAsRead(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markAllNotificationsAsRead, userID)
	return err
}

const markNotificationAsRead = `-- name: MarkNotificationAsRead :exec
UPDATE notifications
SET is_read = TRUE
WHERE id = $1
`

func (q *Queries) MarkNotificationAsRead(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markNotificationAsRead, id)
	return err
}
