// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountUsers(ctx context.Context) (int64, error)
	// internal/db/queries/audit.sql
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error)
	// internal/db/queries/companies.sql
	CreateCompany(ctx context.Context, arg CreateCompanyParams) (Company, error)
	// internal/db/queries/contacts.sql
	CreateContact(ctx context.Context, arg CreateContactParams) (Contact, error)
	// internal/db/queries/deals.sql
	CreateDeal(ctx context.Context, arg CreateDealParams) (Deal, error)
	// internal/db/queries/emails.sql
	CreateEmailAccount(ctx context.Context, arg CreateEmailAccountParams) (EmailAccount, error)
	CreateEmailAttachment(ctx context.Context, arg CreateEmailAttachmentParams) (EmailAttachment, error)
	CreateEmailMessage(ctx context.Context, arg CreateEmailMessageParams) (EmailMessage, error)
	// internal/db/queries/notifications.sql
	CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error)
	// internal/db/queries/sessions.sql
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	// internal/db/queries/todos.sql
	CreateTodo(ctx context.Context, arg CreateTodoParams) (Todo, error)
	// internal/db/queries/users.sql
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteCompany(ctx context.Context, id pgtype.UUID) error
	DeleteContact(ctx context.Context, id pgtype.UUID) error
	DeleteDeal(ctx context.Context, id pgtype.UUID) error
	DeleteRefreshToken(ctx context.Context, tokenHash string) error
	DeleteTodo(ctx context.Context, id pgtype.UUID) error
	DeleteUserRefreshTokens(ctx context.Context, userID pgtype.UUID) error
	GetCompanyByID(ctx context.Context, id pgtype.UUID) (Company, error)
	GetContactByID(ctx context.Context, id pgtype.UUID) (Contact, error)
	GetDealByID(ctx context.Context, id pgtype.UUID) (Deal, error)
	GetEmailAccountByID(ctx context.Context, id pgtype.UUID) (EmailAccount, error)
	GetEmailMessageByID(ctx context.Context, id pgtype.UUID) (EmailMessage, error)
	GetRefreshToken(ctx context.Context, tokenHash string) (RefreshToken, error)
	GetTodoByID(ctx context.Context, id pgtype.UUID) (Todo, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	ListAllNotifications(ctx context.Context, arg ListAllNotificationsParams) ([]Notification, error)
	ListAuditLogsByEntity(ctx context.Context, arg ListAuditLogsByEntityParams) ([]AuditLog, error)
	ListCompanies(ctx context.Context, arg ListCompaniesParams) ([]Company, error)
	ListContacts(ctx context.Context, arg ListContactsParams) ([]Contact, error)
	ListContactsByCompany(ctx context.Context, companyID pgtype.UUID) ([]Contact, error)
	ListDeals(ctx context.Context, arg ListDealsParams) ([]Deal, error)
	ListDealsByStage(ctx context.Context, stage string) ([]Deal, error)
	ListEmailAccounts(ctx context.Context) ([]EmailAccount, error)
	ListEmailAttachmentsByMessage(ctx context.Context, messageID pgtype.UUID) ([]EmailAttachment, error)
	ListEmailMessages(ctx context.Context, arg ListEmailMessagesParams) ([]EmailMessage, error)
	ListEmailMessagesByThread(ctx context.Context, threadID string) ([]EmailMessage, error)
	ListRecentAuditLogs(ctx context.Context, arg ListRecentAuditLogsParams) ([]AuditLog, error)
	ListTodos(ctx context.Context, arg ListTodosParams) ([]Todo, error)
	ListTodosByAssignee(ctx context.Context, assignedTo pgtype.UUID) ([]Todo, error)
	ListUnreadNotifications(ctx context.Context, arg ListUnreadNotificationsParams) ([]Notification, error)
	ListUsers(ctx context.Context) ([]User, error)
	MarkAllNotificationsAsRead(ctx context.Context, userID pgtype.UUID) error
	MarkEmailMessageRead(ctx context.Context, id pgtype.UUID) error
	MarkNotificationAsRead(ctx context.Context, id pgtype.UUID) error
	SearchCompanies(ctx context.Context, arg SearchCompaniesParams) ([]Company, error)
	SearchContacts(ctx context.Context, arg SearchContactsParams) ([]Contact, error)
	UpdateCompany(ctx context.Context, arg UpdateCompanyParams) (Company, error)
	UpdateContact(ctx context.Context, arg UpdateContactParams) (Contact, error)
	UpdateDeal(ctx context.Context, arg UpdateDealParams) (Deal, error)
	UpdateDealStage(ctx context.Context, arg UpdateDealStageParams) (Deal, error)
	UpdateEmailAccountLastSynced(ctx context.Context, arg UpdateEmailAccountLastSyncedParams) error
	UpdateTodo(ctx context.Context, arg UpdateTodoParams) (Todo, error)
	UpdateTodoStatus(ctx context.Context, arg UpdateTodoStatusParams) (Todo, error)
	UpdateUserLastLogin(ctx context.Context, arg UpdateUserLastLoginParams) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) error
	UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) error
	UpdateUserTOTP(ctx context.Context, arg UpdateUserTOTPParams) error
}

var _ Querier = (*Queries)(nil)
