// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: todos.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTodo = `-- name: CreateTodo :one
INSERT INTO todos (
    title,
    description,
    due_date,
    status,
    priority,
    assigned_to,
    contact_id,
    deal_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, title, description, due_date, status, priority, assigned_to, contact_id, deal_id, created_at, updated_at
`

type CreateTodoParams struct {
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	DueDate     pgtype.Timestamptz `json:"due_date"`
	Status      string             `json:"status"`
	Priority    string             `json:"priority"`
	AssignedTo  pgtype.UUID        `json:"assigned_to"`
	ContactID   pgtype.UUID        `json:"contact_id"`
	DealID      pgtype.UUID        `json:"deal_id"`
}

// internal/db/queries/todos.sql
func (q *Queries) CreateTodo(ctx context.Context, arg CreateTodoParams) (Todo, error) {
	row := q.db.QueryRow(ctx, createTodo,
		arg.Title,
		arg.Description,
		arg.DueDate,
		arg.Status,
		arg.Priority,
		arg.AssignedTo,
		arg.ContactID,
		arg.DealID,
	)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.DueDate,
		&i.Status,
		&i.Priority,
		&i.AssignedTo,
		&i.ContactID,
		&i.DealID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTodo = `-- name: DeleteTodo :exec
DELETE FROM todos
WHERE id = $1
`

func (q *Queries) DeleteTodo(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTodo, id)
	return err
}

const getTodoByID = `-- name: GetTodoByID :one
SELECT id, title, description, due_date, status, priority, assigned_to, contact_id, deal_id, created_at, updated_at FROM todos
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTodoByID(ctx context.Context, id pgtype.UUID) (Todo, error) {
	row := q.db.QueryRow(ctx, getTodoByID, id)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.DueDate,
		&i.Status,
		&i.Priority,
		&i.AssignedTo,
		&i.ContactID,
		&i.DealID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTodos = `-- name: ListTodos :many
SELECT id, title, description, due_date, status, priority, assigned_to, contact_id, deal_id, created_at, updated_at FROM todos
ORDER BY due_date ASC NULLS LAST, created_at DESC
LIMIT $1 OFFSET $2
`

type ListTodosParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListTodos(ctx context.Context, arg ListTodosParams) ([]Todo, error) {
	rows, err := q.db.Query(ctx, listTodos, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Todo
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.DueDate,
			&i.Status,
			&i.Priority,
			&i.AssignedTo,
			&i.ContactID,
			&i.DealID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTodosByAssignee = `-- name: ListTodosByAssignee :many
SELECT id, title, description, due_date, status, priority, assigned_to, contact_id, deal_id, created_at, updated_at FROM todos
WHERE assigned_to = $1
ORDER BY due_date ASC NULLS LAST
`

func (q *Queries) ListTodosByAssignee(ctx context.Context, assignedTo pgtype.UUID) ([]Todo, error) {
	rows, err := q.db.Query(ctx, listTodosByAssignee, assignedTo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Todo
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.DueDate,
			&i.Status,
			&i.Priority,
			&i.AssignedTo,
			&i.ContactID,
			&i.DealID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTodo = `-- name: UpdateTodo :one
UPDATE todos
SET title = $2,
    description = $3,
    due_date = $4,
    status = $5,
    priority = $6,
    assigned_to = $7,
    contact_id = $8,
    deal_id = $9,
    updated_at = NOW()
WHERE id = $1
RETURNING id, title, description, due_date, status, priority, assigned_to, contact_id, deal_id, created_at, updated_at
`

type UpdateTodoParams struct {
	ID          pgtype.UUID        `json:"id"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	DueDate     pgtype.Timestamptz `json:"due_date"`
	Status      string             `json:"status"`
	Priority    string             `json:"priority"`
	AssignedTo  pgtype.UUID        `json:"assigned_to"`
	ContactID   pgtype.UUID        `json:"contact_id"`
	DealID      pgtype.UUID        `json:"deal_id"`
}

func (q *Queries) UpdateTodo(ctx context.Context, arg UpdateTodoParams) (Todo, error) {
	row := q.db.QueryRow(ctx, updateTodo,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.DueDate,
		arg.Status,
		arg.Priority,
		arg.AssignedTo,
		arg.ContactID,
		arg.DealID,
	)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.DueDate,
		&i.Status,
		&i.Priority,
		&i.AssignedTo,
		&i.ContactID,
		&i.DealID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTodoStatus = `-- name: UpdateTodoStatus :one
UPDATE todos
SET status = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, title, description, due_date, status, priority, assigned_to, contact_id, deal_id, created_at, updated_at
`

type UpdateTodoStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateTodoStatus(ctx context.Context, arg UpdateTodoStatusParams) (Todo, error) {
	row := q.db.QueryRow(ctx, updateTodoStatus, arg.ID, arg.Status)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.DueDate,
		&i.Status,
		&i.Priority,
		&i.AssignedTo,
		&i.ContactID,
		&i.DealID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
