// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    email,
    password_hash,
    first_name,
    last_name,
    role,
    status
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, email, password_hash, first_name, last_name, role, status, totp_secret_encrypted, totp_enabled, last_login_at, created_at, updated_at, totp_last_used_step
`

type CreateUserParams struct {
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	FirstName    string `json:"first_name"`
	LastName     string `json:"last_name"`
	Role         string `json:"role"`
	Status       string `json:"status"`
}

// internal/db/queries/users.sql
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.FirstName,
		arg.LastName,
		arg.Role,
		arg.Status,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.Role,
		&i.Status,
		&i.TotpSecretEncrypted,
		&i.TotpEnabled,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TotpLastUsedStep,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, first_name, last_name, role, status, totp_secret_encrypted, totp_enabled, last_login_at, created_at, updated_at, totp_last_used_step FROM users
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.Role,
		&i.Status,
		&i.TotpSecretEncrypted,
		&i.TotpEnabled,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TotpLastUsedStep,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, first_name, last_name, role, status, totp_secret_encrypted, totp_enabled, last_login_at, created_at, updated_at, totp_last_used_step FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.Role,
		&i.Status,
		&i.TotpSecretEncrypted,
		&i.TotpEnabled,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TotpLastUsedStep,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, password_hash, first_name, last_name, role, status, totp_secret_encrypted, totp_enabled, last_login_at, created_at, updated_at, totp_last_used_step FROM users
ORDER BY created_at ASC
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.PasswordHash,
			&i.FirstName,
			&i.LastName,
			&i.Role,
			&i.Status,
			&i.TotpSecretEncrypted,
			&i.TotpEnabled,
			&i.LastLoginAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TotpLastUsedStep,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserLastLogin = `-- name: UpdateUserLastLogin :exec
UPDATE users
SET last_login_at = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateUserLastLoginParams struct {
	ID          pgtype.UUID        `json:"id"`
	LastLoginAt pgtype.Timestamptz `json:"last_login_at"`
}

func (q *Queries) UpdateUserLastLogin(ctx context.Context, arg UpdateUserLastLoginParams) error {
	_, err := q.db.Exec(ctx, updateUserLastLogin, arg.ID, arg.LastLoginAt)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET password_hash = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID           pgtype.UUID `json:"id"`
	PasswordHash string      `json:"password_hash"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}

const updateUserRole = `-- name: UpdateUserRole :exec
UPDATE users
SET role = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateUserRoleParams struct {
	ID   pgtype.UUID `json:"id"`
	Role string      `json:"role"`
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) error {
	_, err := q.db.Exec(ctx, updateUserRole, arg.ID, arg.Role)
	return err
}

const updateUserStatus = `-- name: UpdateUserStatus :exec
UPDATE users
SET status = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateUserStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) error {
	_, err := q.db.Exec(ctx, updateUserStatus, arg.ID, arg.Status)
	return err
}

const updateUserTOTP = `-- name: UpdateUserTOTP :exec
UPDATE users
SET totp_secret_encrypted = $2, totp_enabled = $3, totp_last_used_step = $4, updated_at = NOW()
WHERE id = $1
`

type UpdateUserTOTPParams struct {
	ID                  pgtype.UUID `json:"id"`
	TotpSecretEncrypted pgtype.Text `json:"totp_secret_encrypted"`
	TotpEnabled         bool        `json:"totp_enabled"`
	TotpLastUsedStep    int64       `json:"totp_last_used_step"`
}

func (q *Queries) UpdateUserTOTP(ctx context.Context, arg UpdateUserTOTPParams) error {
	_, err := q.db.Exec(ctx, updateUserTOTP,
		arg.ID,
		arg.TotpSecretEncrypted,
		arg.TotpEnabled,
		arg.TotpLastUsedStep,
	)
	return err
}

const updateUserTOTPLastUsedStep = `-- name: UpdateUserTOTPLastUsedStep :exec
UPDATE users
SET totp_last_used_step = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateUserTOTPLastUsedStepParams struct {
	ID               pgtype.UUID `json:"id"`
	TotpLastUsedStep int64       `json:"totp_last_used_step"`
}

func (q *Queries) UpdateUserTOTPLastUsedStep(ctx context.Context, arg UpdateUserTOTPLastUsedStepParams) error {
	_, err := q.db.Exec(ctx, updateUserTOTPLastUsedStep, arg.ID, arg.TotpLastUsedStep)
	return err
}
