// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workflows.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWorkflow = `-- name: CreateWorkflow :one

INSERT INTO workflows (
    id,
    name,
    description,
    trigger_type,
    target_type,
    is_active,
    steps_json
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, name, description, trigger_type, target_type, is_active, steps_json, created_at, updated_at
`

type CreateWorkflowParams struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	TriggerType string `json:"trigger_type"`
	TargetType  string `json:"target_type"`
	IsActive    bool   `json:"is_active"`
	StepsJson   []byte `json:"steps_json"`
}

// internal/db/queries/workflows.sql
func (q *Queries) CreateWorkflow(ctx context.Context, arg CreateWorkflowParams) (Workflow, error) {
	row := q.db.QueryRow(ctx, createWorkflow,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.TriggerType,
		arg.TargetType,
		arg.IsActive,
		arg.StepsJson,
	)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.TriggerType,
		&i.TargetType,
		&i.IsActive,
		&i.StepsJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createWorkflowRun = `-- name: CreateWorkflowRun :one
INSERT INTO workflow_runs (
    id,
    workflow_id,
    target_id,
    target_type,
    target_name,
    status,
    current_step,
    snapshot_json
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, workflow_id, target_id, target_type, target_name, status, current_step, snapshot_json, started_at, completed_at
`

type CreateWorkflowRunParams struct {
	ID           string `json:"id"`
	WorkflowID   string `json:"workflow_id"`
	TargetID     string `json:"target_id"`
	TargetType   string `json:"target_type"`
	TargetName   string `json:"target_name"`
	Status       string `json:"status"`
	CurrentStep  int32  `json:"current_step"`
	SnapshotJson []byte `json:"snapshot_json"`
}

func (q *Queries) CreateWorkflowRun(ctx context.Context, arg CreateWorkflowRunParams) (WorkflowRun, error) {
	row := q.db.QueryRow(ctx, createWorkflowRun,
		arg.ID,
		arg.WorkflowID,
		arg.TargetID,
		arg.TargetType,
		arg.TargetName,
		arg.Status,
		arg.CurrentStep,
		arg.SnapshotJson,
	)
	var i WorkflowRun
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.TargetID,
		&i.TargetType,
		&i.TargetName,
		&i.Status,
		&i.CurrentStep,
		&i.SnapshotJson,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getWorkflowByID = `-- name: GetWorkflowByID :one
SELECT id, name, description, trigger_type, target_type, is_active, steps_json, created_at, updated_at FROM workflows
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetWorkflowByID(ctx context.Context, id string) (Workflow, error) {
	row := q.db.QueryRow(ctx, getWorkflowByID, id)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.TriggerType,
		&i.TargetType,
		&i.IsActive,
		&i.StepsJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWorkflowRuns = `-- name: ListWorkflowRuns :many
SELECT id, workflow_id, target_id, target_type, target_name, status, current_step, snapshot_json, started_at, completed_at FROM workflow_runs
ORDER BY started_at DESC
`

func (q *Queries) ListWorkflowRuns(ctx context.Context) ([]WorkflowRun, error) {
	rows, err := q.db.Query(ctx, listWorkflowRuns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkflowRun
	for rows.Next() {
		var i WorkflowRun
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowID,
			&i.TargetID,
			&i.TargetType,
			&i.TargetName,
			&i.Status,
			&i.CurrentStep,
			&i.SnapshotJson,
			&i.StartedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWorkflowRunByID = `-- name: GetWorkflowRunByID :one
SELECT id, workflow_id, target_id, target_type, target_name, status, current_step, snapshot_json, started_at, completed_at FROM workflow_runs
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetWorkflowRunByID(ctx context.Context, id string) (WorkflowRun, error) {
	row := q.db.QueryRow(ctx, getWorkflowRunByID, id)
	var i WorkflowRun
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.TargetID,
		&i.TargetType,
		&i.TargetName,
		&i.Status,
		&i.CurrentStep,
		&i.SnapshotJson,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const listWorkflows = `-- name: ListWorkflows :many
SELECT id, name, description, trigger_type, target_type, is_active, steps_json, created_at, updated_at FROM workflows
ORDER BY created_at DESC
`

func (q *Queries) ListWorkflows(ctx context.Context) ([]Workflow, error) {
	rows, err := q.db.Query(ctx, listWorkflows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Workflow
	for rows.Next() {
		var i Workflow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.TriggerType,
			&i.TargetType,
			&i.IsActive,
			&i.StepsJson,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWorkflowRunStatus = `-- name: UpdateWorkflowRunStatus :one
UPDATE workflow_runs
SET status = $2,
    current_step = $3,
    completed_at = $4
WHERE id = $1
RETURNING id, workflow_id, target_id, target_type, target_name, status, current_step, snapshot_json, started_at, completed_at
`

type UpdateWorkflowRunStatusParams struct {
	ID          string             `json:"id"`
	Status      string             `json:"status"`
	CurrentStep int32              `json:"current_step"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) UpdateWorkflowRunStatus(ctx context.Context, arg UpdateWorkflowRunStatusParams) (WorkflowRun, error) {
	row := q.db.QueryRow(ctx, updateWorkflowRunStatus,
		arg.ID,
		arg.Status,
		arg.CurrentStep,
		arg.CompletedAt,
	)
	var i WorkflowRun
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.TargetID,
		&i.TargetType,
		&i.TargetName,
		&i.Status,
		&i.CurrentStep,
		&i.SnapshotJson,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}
